name: Test

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # required for requesting the JWT
  contents: read    # required for actions/checkout


jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ["x", "y"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Plan
        id: plan
        run: |
            echo "There are pending changes."

      ## Write for matrix outputs workaround 
      - uses: cloudposse/github-action-matrix-outputs-write@v1
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.region }}
          outputs: |-
            plan-state: ${{ steps.plan.outcome }}

  ## Read matrix outputs 
  read:
    runs-on: ubuntu-latest
    needs: [plan]
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: plan
      - name: Echo
        run: |
          echo "${{ steps.read.outputs.result }}"
      - name: X1
        if: ${{ contains(fromJSON(steps.read.outputs.result)['x'], 'success') }}
        run: |
          echo "X1"

  
